//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKham
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_PhongkhamEntities : DbContext
    {
        public QL_PhongkhamEntities()
            : base("name=QL_PhongkhamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblBenhNhan> tblBenhNhan { get; set; }
        public virtual DbSet<tblDichVu> tblDichVu { get; set; }
        public virtual DbSet<tblDonThuoc> tblDonThuoc { get; set; }
        public virtual DbSet<tblHenKham> tblHenKham { get; set; }
        public virtual DbSet<tblLoaiDichVu> tblLoaiDichVu { get; set; }
        public virtual DbSet<tblLoaiThuoc> tblLoaiThuoc { get; set; }
        public virtual DbSet<tblLoaiVatTu> tblLoaiVatTu { get; set; }
        public virtual DbSet<tblNhaCungCap> tblNhaCungCap { get; set; }
        public virtual DbSet<tblTaiKhoan> tblTaiKhoan { get; set; }
        public virtual DbSet<tblThuoc> tblThuoc { get; set; }
        public virtual DbSet<tblVatTu> tblVatTu { get; set; }
    }
}
