//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKham
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonThuoc
    {
        public int ID { get; set; }
        public Nullable<int> IDNhanVien { get; set; }
        public string TenBacSi { get; set; }
        public Nullable<int> IDBenhNhan { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string Sothe_BHYT { get; set; }
        public string MoTa { get; set; }
        public string TenThuoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DonViTinh { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayTaiKham { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual tblBenhNhan tblBenhNhan { get; set; }
    }
}
