//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKham
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHenKham
    {
        public int ID { get; set; }
        public int IDBenhNhan { get; set; }
        public string HoTen { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string TenBacSi { get; set; }
        public Nullable<int> IDDichVu { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblBenhNhan tblBenhNhan { get; set; }
        public virtual tblDichVu tblDichVu { get; set; }
    }
}
