//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongKham
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVatTu
    {
        public int ID { get; set; }
        public string TenVatTu { get; set; }
        public Nullable<int> IDLoaiVatTu { get; set; }
        public Nullable<int> GiaTien { get; set; }
        public Nullable<int> MaNhaCC { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblLoaiVatTu tblLoaiVatTu { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
    }
}
